routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');



Route::resource('users', 'Admin\UserController');

Auth::routes();

Route::get('home', 'HomeController@index', function(){})->name('home');
Route::get('admin/login', 'AdminController@index', function(){})->name('admin.login');

Route::any('admin/logout', 'Admin\LoginController@logout')->name('admin');

Route::get('logout', 'Auth\LoginController@logout');



Route::GET('admin/home','AdminController@index');
Route::GET('admin/client','ClientController@index');

Route::GET('admin/allUser','AdminController@allUser');
Route::GET('admin/edit/{id}','AdminController@edit', function(){})->name('admin.edit');
Route::PUT('update/{id}','AdminController@update')->name('admin.update');
Route::GET('admin/view/{id}','AdminController@show', function(){})->name('admin.view');
Route::post('destroy/{id}','AdminController@destroy')->name('admin.destroy');
Route::get('admin/create','AdminController@create')->name('admin.create');
Route::post('admin/store','AdminController@store')->name('admin.store');

Route::get('admin/addVersion','VersionController@addVersion')->name('admin.addVersion');
Route::post('admin/storeVersion','VersionController@storeVersion')->name('admin.storeVersion');
Route::POST('deleteVersion/{id}','VersionController@deleteVersion')->name('admin.deleteVersion');

Route::get('getVersion', 'getVersionController@getVersion')->name('getVersion');

//Route::GET('admin/client/api','ApiController@index');

Route::get('admin/logHistory', 'AdminController@logHistory')->name('logHistory');
Route::get('admin/getAllUserLoginHistory', 'AdminController@getAllUserLoginHistory')->name('getAllUserLoginHistory');
Route::get('admin/homePageLoginHistory', 'AdminController@getAllUserLoginHistory')->name('homePageLoginHistory');

Route::get('loginDetails', 'HomeController@UserLoginHistory')->name('loginDetails');

Route::get('getLogDetails', 'HomeController@getLogDetails')->name('getLogDetails');
Route::get('homeLogDetails', 'HomeController@homeLogDetails')->name('homeLogDetails');

Route::get('UserAllSIP', 'HomeController@UserAllSIP')->name('UserAllSIP');

Route::get('UserAllSIPip', 'HomeController@UserAllSIPip')->name('UserAllSIPip');

Route::get('deleteIP/{id}','HomeController@deleteIP')->name('layouts.deleteIP');
Route::GET('admin','Admin\LoginController@showLoginForm')->name('admin.login');
Route::GET('addSipIP','SipIpController@addSipIP')->name('addSipIP');
Route::post('storesipip','SipIpController@storesipip')->name('storesipip');
Route::get('getIPStatus', 'HomeController@getIPStatus')->name('getIPStatus');

Route::get('deleteSIPIP/{id}','HomeController@deleteSIPIP')->name('layouts.deleteSIPIP');

Route::POST('admin','Admin\LoginController@login');

Route::POST('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::GET('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::POST('admin-password/reset','Admin\ResetPasswordController@reset');
Route::GET('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'password',
        'name',
        'last_login_at',
        'last_login_ip',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;
use  App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Hash;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;



class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::latest()->paginate(5);
        return view('admin.users.all', compact('users'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $validatedData = Validator::make($request->all(), [
            'name' => 'required|unique:users|max:40',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6'
        ]);
        if ($validatedData->fails()) {
            return redirect('users/create')
                ->withErrors($validatedData)
                ->withInput();
        }
        $inputs = [
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ];
        if (User::create($inputs)) {

            //return  redirect('users');
            // return redirect("users");
            $userName = str_replace(' ', '_', $request['name']);
            $tableName = strtolower($userName);
            //dd($tableName);
            Schema::create('log_'.$tableName, function (Blueprint $table) {
                $table->increments('id');
                $table->string('adminid');
                $table->string('ip')->nullable();
                $table->string('ip_history')->nullable();
                $table->string('log_ip_add_date')->nullable();
                $table->string('del_ip')->nullable();
                $table->string('log_ip_del_date')->nullable();
                $table->string('sip_ip')->nullable();
                $table->string('sip_ip_history')->nullable();
                $table->string('sip_ip_add_date')->nullable();
                $table->string('del_sip_ip')->nullable();
                $table->string('sip_delete_date')->nullable();
                $table->integer('status')->default('0');
                $table->integer('signature')->default('0');

                $table->timestamps();
            });


            return redirect("users");

        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user = User::find($id);
        return view('users.view', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);
        return view('users.update', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validatedData = Validator::make($request->all(), [
            'name' => 'required|max:40',
            'email' => 'required|email',
            'password' => 'required|min:6'
        ]);
        if ($validatedData->fails()) {
            return redirect('users/create')
                ->withErrors($validatedData)
                ->withInput();
        }

        $inputs = [
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ];
        User::find($id)->update($inputs);

        return redirect("users");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::find($id)->delete();

        return redirect("users");

    }





}

resources/views/admin_old/users/_form.blade.php
                @if (isset($errors) && (count($errors) > 0))
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="form-group">
                    {{ Form::label('name', 'Name') }} <em>*</em>
                    {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'required' => 'required']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('email', 'Email') }} <em>*</em>
                    {{ Form::email('email', null, ['class' => 'form-control', 'id' => 'email']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('password', 'Password') }} <em>*</em>
                    {{ Form::password('password', ['class' => 'form-control', 'id' => 'password']) }}
                </div>

                <div class="form-group">
                    {{ Form::submit('Submit', ['class' => 'btn btn-success']) }}
                </div>

resources/views/admin_old/users/all.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 11:58 AM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop



@section('content')

    <div class="col-sm-12">

        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif

        <div class="panel panel-default">
            <div class="panel-heading">
                User Listing
                <a href="{{ route('users.create') }}" class="btn btn-success btn-xs">Add User</a>
            </div>
            <div class="panel-body">
                @if (count($users))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Created On</th>
                                <th>Last Updated</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at->format('m-d-Y') }}</td>
                                    <td>{{ $user->updated_at->format('m-d-Y') }}</td>
                                    <td>
                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-success btn-xs">Edit</a>
                                        <a href="{{ route('users.show', $user->id) }}" class="btn btn-info btn-xs">View</a>
                                        <form action="{{ route('users.destroy', $user->id) }}" method="POST" style="display:inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-danger btn-xs">
                                                <span>DELETE</span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="text-center">
                        {{ $users->links() }}
                    </div>
                @else
                    <p class="alert alert-info">
                        No Listing Found
                    </p>
                @endif
            </div>
        </div>
        </div>
    </div>

@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop

resources/views/admin_old/users/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 1:44 PM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop



@section('content')
    <section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add Client</h3>
        </div>
        <div class="box-header with-border">


            @if(session()->has('status'))
                <p class="alert alert-info">
                    {{  session()->get('status') }}
                </p>
            @endif
            <div class="col-sm-6">
                <div class="panel panel-default">

                    <div class="panel-body">
                        {{ Form::open(['url' => route('users.store'), 'method' => 'POST' ]) }}
                        @include('admin.users._form')
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>


    </div>
    </section>
@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop

resources/views/admin_old/users/update.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 4:00 PM
 */
?>


@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop




@section('content')
    <div class="container">
        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif
        <div class="col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Update User
                </div>
                <div class="panel-body">

                    {{ Form::model($user, ['url' => route('users.update',$user->id), 'method' => 'PUT' ]) }}
                    @include('users._form')
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection




@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

resources/views/admin_old/users/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 3:49 PM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop

@section('content')

        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif
            <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{--<a href="{{ route('users.index') }}" class="btn btn-success btn-xs">Back</a> --}}
                    User Details
                </div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Name</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->name }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Email</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->email }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Password</label>
                            <div class="col-sm-9">
                                <p class="form-control">********</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Created On</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->created_at->format('m-d-Y') }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Last Updated</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->created_at->format('m-d-Y') }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


@endsection

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')