routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');



Route::resource('users', 'Admin\UserController');

Auth::routes();

Route::get('home', 'HomeController@index', function(){})->name('home');
Route::get('admin/login', 'AdminController@index', function(){})->name('admin.login');

Route::any('admin/logout', 'Admin\LoginController@logout')->name('admin');

Route::get('logout', 'Auth\LoginController@logout');



Route::GET('admin/home','AdminController@index');
Route::GET('admin/client','ClientController@index');

Route::GET('admin/allUser','AdminController@allUser');
Route::GET('admin/edit/{id}','AdminController@edit', function(){})->name('admin.edit');
Route::PUT('update/{id}','AdminController@update')->name('admin.update');
Route::GET('admin/view/{id}','AdminController@show', function(){})->name('admin.view');
Route::post('destroy/{id}','AdminController@destroy')->name('admin.destroy');
Route::get('admin/create','AdminController@create')->name('admin.create');
Route::post('admin/store','AdminController@store')->name('admin.store');

Route::get('admin/addVersion','VersionController@addVersion')->name('admin.addVersion');
Route::post('admin/storeVersion','VersionController@storeVersion')->name('admin.storeVersion');
Route::POST('deleteVersion/{id}','VersionController@deleteVersion')->name('admin.deleteVersion');

Route::get('getVersion', 'getVersionController@getVersion')->name('getVersion');

//Route::GET('admin/client/api','ApiController@index');

Route::get('admin/logHistory', 'AdminController@logHistory')->name('logHistory');
Route::get('admin/getAllUserLoginHistory', 'AdminController@getAllUserLoginHistory')->name('getAllUserLoginHistory');
Route::get('admin/homePageLoginHistory', 'AdminController@getAllUserLoginHistory')->name('homePageLoginHistory');

Route::get('loginDetails', 'HomeController@UserLoginHistory')->name('loginDetails');

Route::get('getLogDetails', 'HomeController@getLogDetails')->name('getLogDetails');
Route::get('homeLogDetails', 'HomeController@homeLogDetails')->name('homeLogDetails');

Route::get('UserAllSIP', 'HomeController@UserAllSIP')->name('UserAllSIP');

Route::get('UserAllSIPip', 'HomeController@UserAllSIPip')->name('UserAllSIPip');

Route::get('deleteIP/{id}','HomeController@deleteIP')->name('layouts.deleteIP');
Route::GET('admin','Admin\LoginController@showLoginForm')->name('admin.login');
Route::GET('addSipIP','SipIpController@addSipIP')->name('addSipIP');
Route::post('storesipip','SipIpController@storesipip')->name('storesipip');
Route::get('getIPStatus', 'HomeController@getIPStatus')->name('getIPStatus');

Route::get('deleteSIPIP/{id}','HomeController@deleteSIPIP')->name('layouts.deleteSIPIP');

Route::POST('admin','Admin\LoginController@login');

Route::POST('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::GET('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::POST('admin-password/reset','Admin\ResetPasswordController@reset');
Route::GET('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

resources/views/admin_old/_form.blade.php
                @if (isset($errors) && (count($errors) > 0))
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="form-group">
                    {{ Form::label('name', 'Name') }} <em>*</em>
                    {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'required' => 'required']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('email', 'Email') }} <em>*</em>
                    {{ Form::email('email', null, ['class' => 'form-control', 'id' => 'email']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('password', 'Password') }} <em>*</em>
                    {{ Form::password('password', ['class' => 'form-control', 'id' => 'password']) }}
                </div>

                <div class="form-group">
                    {{ Form::submit('Submit', ['class' => 'btn btn-success']) }}
                </div>

resources/views/admin_old/allUser.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 11:58 AM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop



@section('content')

    <div class="col-sm-12">

        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif

        <div class="panel panel-default">
            <div class="panel-heading">
                User Listing
                <a href="{{ route('admin.create') }}" class="btn btn-success btn-xs">Add User</a>
            </div>
            <div class="panel-body">
                @if (count($users))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Created On</th>
                                <th>Last Updated</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at->format('m-d-Y') }}</td>
                                    <td>{{ $user->updated_at->format('m-d-Y') }}</td>
                                    <td>
                                        <a href="{{ route('admin.update', $user->id) }}" class="btn btn-success btn-xs">Edit</a>
                                        <a href="{{ route('admin.view', $user->id) }}" class="btn btn-info btn-xs">View</a>
                                        <form action="{{ route('admin.destroy', $user->id) }}" method="POST" style="display:inline-block">
                                            {{ csrf_field() }}
                                            <button class="btn btn-danger btn-xs">
                                                <span>DELETE</span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="text-center">
                        {{ $users->links() }}
                    </div>
                @else
                    <p class="alert alert-info">
                        No Listing Found
                    </p>
                @endif
            </div>
        </div>
    </div>
    </div>

@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop

resources/views/admin_old/client.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 11:58 AM
 */
?>

@extends('admin.layout.master')



@section('title', 'CloudCoder::Firewall')



@section('content_header')

    <h1>Client Dashboard</h1>

@stop



@section('content')

    @if (isset($clientIP))

        <p>Welcome to this beautiful client panel - </p>



        <p> Your IP Is : {{$clientIP}} , Please Wait For Sync..</p>



    @endif
    @if (isset($syncClientIP))

        <p>Welcome to this beautiful client panel - </p>
        <p> Your IP Is : {{$syncClientIP}} , is successfully Synced</p>


    @endif

@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop

resources/views/admin_old/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 1:44 PM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop



@section('content')
    <section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add Client</h3>
        </div>
        <div class="box-header with-border">


            @if(session()->has('status'))
                <p class="alert alert-info">
                    {{  session()->get('status') }}
                </p>
            @endif
            <div class="col-sm-6">
                <div class="panel panel-default">

                    <div class="panel-body">
                        {{ Form::open(['url' => route('admin.store'), 'method' => 'POST' ]) }}
                        @include('admin._form')
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>


    </div>
    </section>
@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop

resources/views/admin_old/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CloudCoder::Firewall</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('vendor/adminlte/vendor/font-awesome/css/font-awesome.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('vendor/adminlte/vendor/Ionicons/css/ionicons.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('vendor/adminlte/dist/css/AdminLTE.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('vendor/adminlte/dist/css/skins/skin-blue.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendor/adminlte/dist/css/custom.style.css')}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="javascript:void('0')"><b>Admin</b>Login</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form method="POST" action="{{ route('admin.login') }}">
            @csrf
            <div class="form-group has-feedback">
                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>

                @if ($errors->has('email'))
                    <span class="invalid-email" role="alert">
                          <strong>{{ $errors->first('email') }}</strong>
                    </span>
                @endif
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                @if ($errors->has('password'))
                    <span class="invalid-password" role="alert">
                         <strong>{{ $errors->first('password') }}</strong>
                     </span>
                @endif
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="form-check">
                        <input class="" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                        <label class="form-check-label" for="remember">
                            {{ __('Remember Me') }}
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Sign In') }}
                    </button>


                </div>
                <!-- /.col -->
            </div>
            <a class="btn btn-link forgetpass"  href="{{ route('admin.password.request') }}">
                {{ __('Forgot Your Password?') }}
            </a>
        </form>


        <!-- /.social-auth-links -->




    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{asset('vendor/adminlte/vendor/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('vendor/adminlte/vendor/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- iCheck -->
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

resources/views/admin_old/register.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('register') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin_old/update.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 4:00 PM
 */
?>


@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop




@section('content')
    <div class="container">
        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif
        <div class="col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Update User
                </div>
                <div class="panel-body">

                    {{ Form::model($user, ['url' => route('users.update',$user->id), 'method' => 'PUT' ]) }}
                    @include('admin._form')
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection




@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

resources/views/admin_old/verify.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Verify Your Email Address') }}</div>

                <div class="card-body">
                    @if (session('resent'))
                        <div class="alert alert-success" role="alert">
                            {{ __('A fresh verification link has been sent to your email address.') }}
                        </div>
                    @endif

                    {{ __('Before proceeding, please check your email for a verification link.') }}
                    {{ __('If you did not receive the email') }}, <a href="{{ route('verification.resend') }}">{{ __('click here to request another') }}</a>.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin_old/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 3:49 PM
 */
?>

@extends('adminlte::page')



@section('title', 'Dashboard')



@section('content_header')

    <h1>Dashboard</h1>

@stop

@section('content')

        @if(session()->has('status'))
            <p class="alert alert-info">
                {{  session()->get('status') }}
            </p>
        @endif
            <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{--<a href="{{ route('users.index') }}" class="btn btn-success btn-xs">Back</a> --}}
                    User Details
                </div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Name</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->name }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Email</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->email }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Password</label>
                            <div class="col-sm-9">
                                <p class="form-control">********</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Created On</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->created_at->format('m-d-Y') }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="name">Last Updated</label>
                            <div class="col-sm-9">
                                <p class="form-control">{{ $user->created_at->format('m-d-Y') }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


@endsection

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

resources/views/admin_old/welcome2.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: tanvi
 * Date: 11/18/2018
 * Time: 11:58 AM
 */
?>

@extends('adminlte::page')



@section('title', 'CloudCoder::Firewall')



@section('content_header')

    <h1>Admin Dashboard</h1>

@stop



@section('content')

    <p>Welcome to this beautiful admin panel - HDTuto.com.</p>

@stop



@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop



@section('js')

    <script> console.log('Hi!'); </script>

@stop